//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCalender
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CalenderDate { get; set; }
        public Nullable<System.TimeSpan> CalenderTime { get; set; }
        public Nullable<bool> IsappointmentBooked { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
