//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsLogin { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
